spring:
  application:
    name: auth-service

  # Config Server configuration
#  config:
#    import: optional:configserver:http://localhost:8888

# Eureka Client configuration
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka